name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]   # or master

permissions:
  contents: write   # needed to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (if you use npm/yarn)
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build   # build script

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # folder to deploy
          publish_branch: gh-pages
